# Generated by Django 4.2.5 on 2023-10-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(choices=[(53, '53')]),
        ),
    ]
