# Generated by Django 4.2.5 on 2023-10-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_seattrip_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
