# Generated by Django 4.2.5 on 2023-10-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_time',
        ),
    ]
