# Generated by Django 4.2.5 on 2023-11-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_order_seattrip_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seattrip",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_seat_trip",
                to="trips.order",
            ),
        ),
    ]
