# Generated by Django 4.2.5 on 2023-10-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_trip_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='availabe_tickets',
        ),
    ]
